//! Render the OSM Rails harvest → Rust structs (ClassView × FieldMask → struct
//! + `ActionDef` methods), one file per class.
//! `cargo run -p ogar-render-askama --example render_osm -- <osm-root> <out-dir>`
use lance_graph_contract::class_view::FieldMask;
use ogar_render_askama::render_class_with_methods;
use std::fs;
use std::path::Path;

/// Rails class name → OGAR canonical concept (the `ogar-vocab` codebook, Geo
/// domain `0x0FXX`). `None` for classes that aren't canonical geodata concepts
/// (diary / message / issue / … app-social entities) — they render without a
/// `CLASS_ID`.
fn ground(rails: &str) -> Option<&'static str> {
    Some(match rails {
        "Node" | "OldNode" => "osm_node",
        "Way" | "OldWay" => "osm_way",
        "Relation" | "OldRelation" => "osm_relation",
        "Changeset" => "osm_changeset",
        "NodeTag" | "WayTag" | "RelationTag" | "OldNodeTag" | "OldWayTag"
        | "OldRelationTag" => "osm_element_tag",
        "RelationMember" | "OldRelationMember" => "osm_relation_member",
        "WayNode" | "OldWayNode" => "osm_way_node",
        "Note" => "osm_note",
        "Trace" => "osm_gpx_trace",
        "User" => "osm_user",
        _ => return None,
    })
}

/// PascalCase / dotted name → snake_case module/file stem.
fn snake(name: &str) -> String {
    let mut out = String::new();
    let mut prev_alnum_lower = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if c.is_ascii_uppercase() && prev_alnum_lower {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev_alnum_lower = c.is_ascii_lowercase() || c.is_ascii_digit();
        } else {
            if !out.is_empty() && !out.ends_with('_') {
                out.push('_');
            }
            prev_alnum_lower = false;
        }
    }
    let s = out.trim_matches('_').to_string();
    if s.is_empty() {
        "anon".into()
    } else {
        s
    }
}

fn main() {
    let mut args = std::env::args().skip(1);
    let src = args
        .next()
        .unwrap_or_else(|| "/home/user/_src-osm-website".into());
    let out_arg = args.next().unwrap_or_else(|| {
        "/home/user/OGAR/.claude/harvest/osm-website-rs/crates/osm-domain/src/generated".into()
    });
    let out = Path::new(&out_arg);
    fs::create_dir_all(out).unwrap();

    let src_path = Path::new(&src);
    let mut classes = ogar_from_rails::extract_with(src_path, "osm");
    if classes.is_empty() {
        classes = ogar_from_rails::extract_with(&src_path.join("app/models"), "osm");
    }
    classes.sort_by(|a, b| a.name.cmp(&b.name));

    // Grounding: map each Rails class onto its OGAR canonical concept (the 15%
    // ontological step the mechanical lift can't infer) so the render emits
    // `CLASS_ID` from the codebook. Versioned `Old*` classes ground to the same
    // concept as their base (temporal axis, not a new id).
    for c in classes.iter_mut() {
        if let Some(concept) = ground(&c.name) {
            c.canonical_concept = Some(concept.to_string());
        }
    }

    let mut mods: Vec<String> = Vec::new();
    for c in &classes {
        let stem = snake(&c.name);
        let code = render_class_with_methods(c, FieldMask(u64::MAX), &[]).expect("render");
        let header = format!(
            "// @generated by ogar-render-askama — ruff → OGAR transpile\n\
             // source class: {} (openstreetmap-website app/models)\n\n",
            c.name
        );
        fs::write(out.join(format!("{stem}.rs")), format!("{header}{code}")).unwrap();
        mods.push(stem);
    }
    mods.sort();
    mods.dedup();
    let mod_body: String = mods.iter().map(|m| format!("pub mod {m};\n")).collect();
    fs::write(
        out.join("mod.rs"),
        format!(
            "// @generated module index — {} OSM domain classes (ruff → OGAR render)\n{mod_body}",
            mods.len()
        ),
    )
    .unwrap();

    println!("rendered {} classes -> {}", classes.len(), out.display());
}
