//! Render the OSM Rails harvest → a **Python import-shape** package — the
//! Python counterpart of `render_osm` (which emits Rust). Same substrate, two
//! back-ends: proves OGAR is a bidirectional per-class transpiler whose emit
//! side is language-pluggable.
//!
//! `cargo run -p ogar-render-askama --example render_python -- <osm-root> <out-dir>`
//!
//! Emits, under `<out-dir>/osm/`:
//! - `__init__.py`  — package marker; re-exports the models + `CLASS_IDS`.
//! - `models.py`    — one `@dataclass` per THINK class (associations → typed
//!                    id fields), each carrying its `CLASS_ID`.
//! - `<part_of>.py` — the DO arm: one module per container, `def <is_a>(inp)`
//!                    free functions (`osm.node.show(inp)`), NOT methods.
//!
//! and, one level up, `ogar_sdk.py` — the thin substrate-pull SDK: the codebook
//! as a dict + `class_id(concept)` / `render_classid(concept, app_prefix)`, the
//! Python mirror of the Rust `lance_graph_contract::ogar_codebook` contract. The
//! same SDK pulls odoo (`0x02`) concepts — the shape is domain-agnostic.
use ogar_vocab::{canonical_concept_id, AssociationKind};
use std::collections::BTreeMap;
use std::fs;
use std::path::Path;

/// Rails class name → OGAR canonical concept (Geo domain `0x0FXX`). `None` for
/// app-social entities that aren't canonical geodata concepts.
fn ground(rails: &str) -> Option<&'static str> {
    Some(match rails {
        "Node" | "OldNode" => "osm_node",
        "Way" | "OldWay" => "osm_way",
        "Relation" | "OldRelation" => "osm_relation",
        "Changeset" => "osm_changeset",
        "NodeTag" | "WayTag" | "RelationTag" | "OldNodeTag" | "OldWayTag"
        | "OldRelationTag" => "osm_element_tag",
        "RelationMember" | "OldRelationMember" => "osm_relation_member",
        "WayNode" | "OldWayNode" => "osm_way_node",
        "Note" => "osm_note",
        "Trace" => "osm_gpx_trace",
        "User" => "osm_user",
        _ => return None,
    })
}

/// PascalCase / dotted → snake_case (module / fn / field stem).
fn snake(name: &str) -> String {
    let mut out = String::new();
    let mut prev = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if c.is_ascii_uppercase() && prev {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev = c.is_ascii_lowercase() || c.is_ascii_digit();
        } else {
            if !out.is_empty() && !out.ends_with('_') {
                out.push('_');
            }
            prev = false;
        }
    }
    let s = out.trim_matches('_').to_string();
    if s.is_empty() {
        "anon".into()
    } else {
        s
    }
}

/// A safe Python identifier: snake + escape the handful of keywords a container
/// or verb hits + avoid a leading digit.
fn pyify(name: &str) -> String {
    let s = snake(name);
    const KW: &[&str] = &[
        "False", "None", "True", "and", "as", "assert", "async", "await", "break", "class",
        "continue", "def", "del", "elif", "else", "except", "finally", "for", "from", "global",
        "if", "import", "in", "is", "lambda", "nonlocal", "not", "or", "pass", "raise", "return",
        "try", "while", "with", "yield", "match", "case", "type",
    ];
    if s.is_empty() {
        "action".into()
    } else if KW.contains(&s.as_str()) {
        format!("{s}_")
    } else if s.as_bytes()[0].is_ascii_digit() {
        format!("_{s}")
    } else {
        s
    }
}

/// OGAR attribute `type_name` → Python annotation.
fn py_type(type_name: Option<&str>) -> &'static str {
    match type_name.unwrap_or("") {
        "string" | "str" | "text" => "str",
        "u8" | "u16" | "u32" | "u64" | "i8" | "i16" | "i32" | "i64" | "integer" | "int" => "int",
        "bool" | "boolean" => "bool",
        "f32" | "f64" | "float" | "decimal" => "float",
        _ => "Any",
    }
}

fn main() {
    let mut args = std::env::args().skip(1);
    let src = args
        .next()
        .unwrap_or_else(|| "/home/user/_src-osm-website".into());
    let out_arg = args.next().unwrap_or_else(|| {
        "/home/user/OGAR/.claude/harvest/osm-website-rs/python".into()
    });
    let out = Path::new(&out_arg);
    let pkg = out.join("osm");
    fs::create_dir_all(&pkg).unwrap();

    let src_path = Path::new(&src);
    let mut classes = ogar_from_rails::extract_with(src_path, "osm");
    if classes.is_empty() {
        classes = ogar_from_rails::extract_with(&src_path.join("app/models"), "osm");
    }
    classes.sort_by(|a, b| a.name.cmp(&b.name));
    for c in classes.iter_mut() {
        if let Some(concept) = ground(&c.name) {
            c.canonical_concept = Some(concept.to_string());
        }
    }

    // ── models.py — one @dataclass per THINK class ──
    let mut models = String::from(
        "\"\"\"@generated by ogar-render-askama render_python — ruff → OGAR (THINK arm).\n\
         OSM domain models as dataclasses; associations become typed id fields.\n\"\"\"\n\
         from __future__ import annotations\nfrom dataclasses import dataclass, field\n\
         from typing import Any, List, Optional\n\n",
    );
    let mut class_ids: Vec<(String, u16)> = Vec::new();
    for c in &classes {
        let cls = c.name.replace("::", "_");
        models.push_str(&format!("@dataclass\nclass {cls}:\n"));
        if let Some(concept) = &c.canonical_concept {
            if let Some(id) = canonical_concept_id(concept) {
                models.push_str(&format!(
                    "    CLASS_ID: int = 0x{id:04X}  # canonical concept `{concept}`\n"
                ));
                class_ids.push((cls.clone(), id));
            }
        }
        let mut wrote = false;
        for a in &c.attributes {
            models.push_str(&format!(
                "    {}: Optional[{}] = None\n",
                pyify(&a.name),
                py_type(a.type_name.as_deref())
            ));
            wrote = true;
        }
        for a in &c.associations {
            let fname = pyify(&a.name);
            match a.kind {
                AssociationKind::HasMany | AssociationKind::HasAndBelongsToMany => {
                    models.push_str(&format!(
                        "    {fname}: List[int] = field(default_factory=list)\n"
                    ));
                }
                // BelongsTo / HasOne / any future single-target kind → one FK id.
                _ => {
                    models.push_str(&format!("    {fname}: Optional[int] = None\n"));
                }
            }
            wrote = true;
        }
        if !wrote {
            models.push_str("    pass\n");
        }
        models.push('\n');
    }
    fs::write(pkg.join("models.py"), &models).unwrap();

    // ── DO arm: a faithful osm/controllers/ subpackage — one module per source
    // controller by its own verbatim name (`osm.controllers.nodes.show(inp)`),
    // re-exported at `osm.<name>` for the ergonomic surface. Mirrors the Rust
    // `controllers` module + `pub use controllers::*`. No singularisation. ──
    let ctrl = pkg.join("controllers");
    fs::create_dir_all(&ctrl).unwrap();
    let rail_root: &Path = if src_path.join("app/controllers").is_dir() {
        src_path
    } else if src_path.ends_with("app/models") {
        src_path.parent().and_then(|p| p.parent()).unwrap_or(src_path)
    } else {
        src_path
    };
    let rail = ogar_from_rails::extract_action_rail(rail_root, "osm");
    let mut tree: BTreeMap<String, BTreeMap<String, Vec<(String, String)>>> = BTreeMap::new();
    for r in &rail {
        tree.entry(r.part_of.clone())
            .or_default()
            .entry(r.is_a.clone())
            .or_default()
            .push((r.controller.clone(), r.action.clone()));
    }
    let mut containers: Vec<String> = Vec::new();
    let mut fn_count = 0usize;
    for (part_of, isas) in &tree {
        let module = pyify(part_of);
        let mut body = format!(
            "\"\"\"@generated DO arm — faithful mirror of the `{part_of}` controller.\n\
             `osm.controllers.{module}.<is_a>(inp)` free functions (re-exported as\n\
             `osm.{module}`); standalone, not methods on the model. Call:\n\
             `osm.controllers.{module}.show(inp)`.\n\"\"\"\n\
             from typing import Any\n\n\
             Input = dict   # the Rails params bag; typed params are the next ruff brick\n\
             Output = Any\n\n",
        );
        let mut seen = std::collections::HashSet::new();
        for (is_a, sources) in isas {
            let fname = pyify(is_a);
            if !seen.insert(fname.clone()) {
                continue;
            }
            let mut srcs: Vec<String> =
                sources.iter().map(|(c, a)| format!("{c}#{a}")).collect();
            srcs.sort();
            srcs.dedup();
            let cite = if srcs.len() == 1 {
                format!("Source: {}", srcs[0])
            } else {
                format!("Sources (canonical tile): {}", srcs.join(", "))
            };
            body.push_str(&format!(
                "def {fname}(inp: Input) -> Output:\n    \
                 \"\"\"`{part_of}:{is_a}` — DO arm. {cite}.\"\"\"\n    \
                 raise NotImplementedError(\"port {}\")\n\n",
                srcs[0]
            ));
            fn_count += 1;
        }
        fs::write(ctrl.join(format!("{module}.py")), &body).unwrap();
        containers.push(module);
    }
    containers.sort();
    containers.dedup();

    // osm/controllers/__init__.py — the subpackage; re-imports each controller.
    let mut ctrl_init = String::from(
        "\"\"\"@generated `controllers` subpackage — faithful 1:1 mirror of\n\
         `app/controllers/`, each module named by its controller (verbatim).\n\"\"\"\n",
    );
    for m in &containers {
        ctrl_init.push_str(&format!("from . import {m} as {m}\n"));
    }
    fs::write(ctrl.join("__init__.py"), &ctrl_init).unwrap();

    // ── osm/__init__.py — package re-exports + CLASS_IDS ──
    // Re-export each controller at the package root (the ergonomic surface over
    // the faithful `controllers` subpackage — `osm.nodes` ≡ `osm.controllers.nodes`).
    let mut init = String::from(
        "\"\"\"@generated OSM package (ruff → OGAR, Python import shape).\n\
         Models: `from osm.models import Node`.\n\
         DO arm (faithful): `osm.controllers.nodes.show(inp)`.\n\
         DO arm (re-exported): `osm.nodes.show(inp)`.\n\"\"\"\n\
         from . import models as models\n\
         from . import controllers as controllers\n",
    );
    for m in &containers {
        init.push_str(&format!("from .controllers import {m} as {m}\n"));
    }
    init.push_str("\nCLASS_IDS = {\n");
    for (cls, id) in &class_ids {
        init.push_str(&format!("    \"{cls}\": 0x{id:04X},\n"));
    }
    init.push_str("}\n");
    fs::write(pkg.join("__init__.py"), &init).unwrap();

    // ── ogar_sdk.py — the substrate-pull SDK (domain-agnostic) ──
    // The codebook subset the SDK ships is domain-agnostic: OSM (0x0F) here,
    // plus a couple odoo/commerce (0x02) concepts to show cross-app pull.
    let sdk = r#""""ogar_sdk — thin Python client over the OGAR codebook substrate.

The Python mirror of Rust `lance_graph_contract::ogar_codebook`: pull a concept's
stable classid, or compose a render-classid with an app prefix. Domain-agnostic —
OSM (0x0F) and odoo/commerce (0x02) pull identically.

    >>> from ogar_sdk import class_id, render_classid
    >>> class_id("osm_node")
    3841
    >>> hex(render_classid("account_move", 0x0002))   # odoo, canon-high
    '0x2020002'
"""
from typing import Optional

# The pulled substrate — a subset of ogar-vocab's CODEBOOK (concept -> u16 id).
CODEBOOK = {
    # 0x0F — Geo (OpenStreetMap)
    "osm_node": 0x0F01, "osm_way": 0x0F02, "osm_relation": 0x0F03,
    "osm_changeset": 0x0F04, "osm_element_tag": 0x0F05, "osm_relation_member": 0x0F06,
    "osm_way_node": 0x0F07, "osm_note": 0x0F08, "osm_gpx_trace": 0x0F09, "osm_user": 0x0F0A,
    # 0x02 — Commerce (odoo / ERP) — same pull, different domain
    "commercial_document": 0x0202, "product": 0x0207, "accounting_account": 0x0208,
}
# Convenience alias used in the odoo docstring example.
CODEBOOK["account_move"] = CODEBOOK["commercial_document"]


def class_id(concept: str) -> Optional[int]:
    """Resolve a canonical-concept string to its stable u16 codebook id."""
    return CODEBOOK.get(concept)


def render_classid(concept: str, app_prefix: int) -> Optional[int]:
    """Compose a 32-bit render classid: canon (concept) HIGH, custom (prefix) LOW.

    Mirrors the post-2026-07-02 canon-high flip: `(concept << 16) | prefix`.
    """
    cid = class_id(concept)
    if cid is None:
        return None
    return (cid << 16) | (app_prefix & 0xFFFF)
"#;
    fs::write(out.join("ogar_sdk.py"), sdk).unwrap();

    println!(
        "rendered Python: {} models ({} with CLASS_ID) + DO arm {fn_count} fns across {} \
         modules; SDK ogar_sdk.py -> {}",
        classes.len(),
        class_ids.len(),
        containers.len(),
        out.display()
    );
}
