//! Render the OSM Rails harvest → Rust structs (ClassView × FieldMask → struct
//! + `ActionDef` methods), one file per class.
//! `cargo run -p ogar-render-askama --example render_osm -- <osm-root> <out-dir>`
use lance_graph_contract::class_view::FieldMask;
use ogar_render_askama::render_class_with_methods;
use ogar_vocab::canonical_concept_id;
use std::fs;
use std::path::Path;

/// Resolve an association target (a class_name like `"User"` or a relation
/// name like `"changeset"`) to its OGAR canonical concept, if grounded.
fn ground_target(target: &str) -> Option<&'static str> {
    // Try the raw name, then a PascalCase-ish normalisation of a snake name.
    ground(target).or_else(|| {
        let pascal: String = target
            .split('_')
            .map(|w| {
                let mut ch = w.chars();
                ch.next()
                    .map(|c| c.to_ascii_uppercase().to_string() + ch.as_str())
                    .unwrap_or_default()
            })
            .collect();
        ground(&pascal)
    })
}

/// Rails class name → OGAR canonical concept (the `ogar-vocab` codebook, Geo
/// domain `0x0FXX`). `None` for classes that aren't canonical geodata concepts
/// (diary / message / issue / … app-social entities) — they render without a
/// `CLASS_ID`.
fn ground(rails: &str) -> Option<&'static str> {
    Some(match rails {
        "Node" | "OldNode" => "osm_node",
        "Way" | "OldWay" => "osm_way",
        "Relation" | "OldRelation" => "osm_relation",
        "Changeset" => "osm_changeset",
        "NodeTag" | "WayTag" | "RelationTag" | "OldNodeTag" | "OldWayTag"
        | "OldRelationTag" => "osm_element_tag",
        "RelationMember" | "OldRelationMember" => "osm_relation_member",
        "WayNode" | "OldWayNode" => "osm_way_node",
        "Note" => "osm_note",
        "Trace" => "osm_gpx_trace",
        "User" => "osm_user",
        _ => return None,
    })
}

/// PascalCase / dotted name → snake_case module/file stem.
fn snake(name: &str) -> String {
    let mut out = String::new();
    let mut prev_alnum_lower = false;
    for c in name.chars() {
        if c.is_ascii_alphanumeric() {
            if c.is_ascii_uppercase() && prev_alnum_lower {
                out.push('_');
            }
            out.push(c.to_ascii_lowercase());
            prev_alnum_lower = c.is_ascii_lowercase() || c.is_ascii_digit();
        } else {
            if !out.is_empty() && !out.ends_with('_') {
                out.push('_');
            }
            prev_alnum_lower = false;
        }
    }
    let s = out.trim_matches('_').to_string();
    if s.is_empty() {
        "anon".into()
    } else {
        s
    }
}

fn main() {
    let mut args = std::env::args().skip(1);
    let src = args
        .next()
        .unwrap_or_else(|| "/home/user/_src-osm-website".into());
    let out_arg = args.next().unwrap_or_else(|| {
        "/home/user/OGAR/.claude/harvest/osm-website-rs/crates/osm-domain/src/generated".into()
    });
    let out = Path::new(&out_arg);
    fs::create_dir_all(out).unwrap();

    let src_path = Path::new(&src);
    let mut classes = ogar_from_rails::extract_with(src_path, "osm");
    if classes.is_empty() {
        classes = ogar_from_rails::extract_with(&src_path.join("app/models"), "osm");
    }
    classes.sort_by(|a, b| a.name.cmp(&b.name));

    // Grounding: map each Rails class onto its OGAR canonical concept (the 15%
    // ontological step the mechanical lift can't infer) so the render emits
    // `CLASS_ID` from the codebook. Versioned `Old*` classes ground to the same
    // concept as their base (temporal axis, not a new id).
    for c in classes.iter_mut() {
        if let Some(concept) = ground(&c.name) {
            c.canonical_concept = Some(concept.to_string());
        }
    }

    // ── DO-arm: harvest app/controllers → ActionDefs keyed by model. OGAR is
    // Open Graph of Active *Record* — Model + Controller — so the controller
    // actions attach as Rust methods on the model struct. ──
    let actions_by_model: std::collections::HashMap<String, Vec<ogar_vocab::ActionDef>> =
        ogar_from_rails::extract_actions(src_path, "osm")
            .into_iter()
            .collect();
    let total_actions: usize = actions_by_model.values().map(Vec::len).sum();

    let mut mods: Vec<String> = Vec::new();
    for c in &classes {
        let stem = snake(&c.name);
        let actions = actions_by_model.get(&c.name).map(Vec::as_slice).unwrap_or(&[]);
        let code = render_class_with_methods(c, FieldMask(u64::MAX), actions).expect("render");
        let header = format!(
            "// @generated by ogar-render-askama — ruff → OGAR transpile\n\
             // source class: {} (openstreetmap-website app/models)\n\n",
            c.name
        );
        fs::write(out.join(format!("{stem}.rs")), format!("{header}{code}")).unwrap();
        mods.push(stem);
    }
    mods.sort();
    mods.dedup();
    let mod_body: String = mods.iter().map(|m| format!("pub mod {m};\n")).collect();
    fs::write(
        out.join("mod.rs"),
        format!(
            "// @generated module index — {} OSM domain classes (ruff → OGAR render)\n{mod_body}",
            mods.len()
        ),
    )
    .unwrap();

    // ── OSM association graph as classid-keyed SPO edges (lance-graph feed) ──
    // node/way/relation as a graph: each grounded class is a subject carrying a
    // CLASS_ID; each association is an edge to a target concept (classid where
    // the target grounds).
    let mut spo = String::from(
        "# OSM association graph — SPO edges (ruff → OGAR), classid-keyed\n\
         # subject_concept[classid] --assoc_kind:name--> object[classid]\n\n",
    );
    let mut edges = 0usize;
    for c in &classes {
        let s_concept = c.canonical_concept.as_deref().unwrap_or("-");
        let s_id = c
            .canonical_concept
            .as_deref()
            .and_then(canonical_concept_id)
            .map(|i| format!("0x{i:04X}"))
            .unwrap_or_else(|| "----".into());
        for a in &c.associations {
            let target = a.class_name.clone().unwrap_or_else(|| a.name.clone());
            let o_id = ground_target(&target)
                .and_then(canonical_concept_id)
                .map(|i| format!("0x{i:04X}"))
                .unwrap_or_else(|| "----".into());
            spo.push_str(&format!(
                "{s_concept}[{s_id}] --{:?}:{}--> {target}[{o_id}]\n",
                a.kind, a.name
            ));
            edges += 1;
        }
    }
    if let Some(root) = out.ancestors().nth(4) {
        let hp = root.join("harvest");
        fs::create_dir_all(&hp).ok();
        fs::write(hp.join("osm_graph.spo"), &spo).unwrap();
    }

    // ── Action rail: (part_of : is_a) — the castable V3 action shape ──
    let rail = ogar_from_rails::extract_action_rail(src_path, "osm");
    let mut rt = String::from(
        "# OSM action rail — (part_of : is_a), the V3 castable action shape\n\
         # a u8:u8 HHTL tile per action; cast = fix one axis, walk the other\n\
         # part_of[id]:is_a[id]\\tcontroller#action\n\n",
    );
    let mut parts: std::collections::BTreeSet<(u8, String)> = std::collections::BTreeSet::new();
    let mut isas: std::collections::BTreeSet<(u8, String)> = std::collections::BTreeSet::new();
    for r in &rail {
        rt.push_str(&format!(
            "{}[0x{:02X}]:{}[0x{:02X}]\t{}#{}\n",
            r.part_of, r.part_of_id, r.is_a, r.is_a_id, r.controller, r.action
        ));
        parts.insert((r.part_of_id, r.part_of.clone()));
        isas.insert((r.is_a_id, r.is_a.clone()));
    }
    rt.push_str(&format!("\n# is_a axis ({} archetypes): ", isas.len()));
    rt.push_str(
        &isas
            .iter()
            .map(|(i, n)| format!("{n}=0x{i:02X}"))
            .collect::<Vec<_>>()
            .join(" "),
    );
    rt.push_str(&format!("\n# part_of axis ({} containers): ", parts.len()));
    rt.push_str(
        &parts
            .iter()
            .map(|(i, n)| format!("{n}=0x{i:02X}"))
            .collect::<Vec<_>>()
            .join(" "),
    );
    rt.push('\n');
    if let Some(root) = out.ancestors().nth(4) {
        fs::write(root.join("harvest/osm_actions.rail"), &rt).unwrap();
    }

    println!(
        "rendered {} classes ({total_actions} DO-arm methods across {} model \
         containers); action rail = {} (part_of:is_a) tiles [{} part_of x {} is_a]; \
         {edges} SPO edges -> {}",
        classes.len(),
        actions_by_model.len(),
        rail.len(),
        parts.len(),
        isas.len(),
        out.display()
    );
}
