"""@generated by ogar-render-askama render_python — ruff → OGAR (THINK arm).
OSM domain models as dataclasses; associations become typed id fields.
"""
from __future__ import annotations
from dataclasses import dataclass, field
from typing import Any, List, Optional

@dataclass
class Acl:
    pass

@dataclass
class ApplicationRecord:
    pass

@dataclass
class Changeset:
    CLASS_ID: int = 0x0F04  # canonical concept `osm_changeset`
    user: Optional[int] = None
    changeset_tags: List[int] = field(default_factory=list)
    nodes: List[int] = field(default_factory=list)
    ways: List[int] = field(default_factory=list)
    relations: List[int] = field(default_factory=list)
    old_nodes: List[int] = field(default_factory=list)
    old_ways: List[int] = field(default_factory=list)
    old_relations: List[int] = field(default_factory=list)
    comments: List[int] = field(default_factory=list)
    subscriptions: List[int] = field(default_factory=list)
    subscribers: List[int] = field(default_factory=list)

@dataclass
class ChangesetComment:
    changeset: Optional[int] = None
    author: Optional[int] = None

@dataclass
class ChangesetSubscription:
    subscriber: Optional[int] = None
    changeset: Optional[int] = None

@dataclass
class ChangesetTag:
    changeset: Optional[int] = None

@dataclass
class Community:
    pass

@dataclass
class DiaryComment:
    user: Optional[int] = None
    diary_entry: Optional[int] = None

@dataclass
class DiaryEntry:
    user: Optional[int] = None
    language: Optional[int] = None
    comments: List[int] = field(default_factory=list)
    visible_comments: List[int] = field(default_factory=list)
    subscriptions: List[int] = field(default_factory=list)
    subscribers: List[int] = field(default_factory=list)

@dataclass
class DiaryEntrySubscription:
    user: Optional[int] = None
    diary_entry: Optional[int] = None

@dataclass
class Follow:
    follower: Optional[int] = None
    following: Optional[int] = None

@dataclass
class GeoRecord_Coord:
    pass

@dataclass
class Issue:
    reportable: Optional[int] = None
    reported_user: Optional[int] = None
    user_resolved: Optional[int] = None
    user_updated: Optional[int] = None
    reports: List[int] = field(default_factory=list)
    comments: List[int] = field(default_factory=list)

@dataclass
class IssueComment:
    issue: Optional[int] = None
    user: Optional[int] = None

@dataclass
class Language:
    diary_entries: List[int] = field(default_factory=list)

@dataclass
class Message:
    sender: Optional[int] = None
    recipient: Optional[int] = None

@dataclass
class ModerationZone:
    creator: Optional[int] = None
    revoker: Optional[int] = None

@dataclass
class Node:
    CLASS_ID: int = 0x0F01  # canonical concept `osm_node`
    changeset: Optional[int] = None
    old_nodes: List[int] = field(default_factory=list)
    way_nodes: List[int] = field(default_factory=list)
    ways: List[int] = field(default_factory=list)
    element_tags: List[int] = field(default_factory=list)
    old_way_nodes: List[int] = field(default_factory=list)
    ways_via_history: List[int] = field(default_factory=list)
    containing_relation_members: List[int] = field(default_factory=list)
    containing_relations: List[int] = field(default_factory=list)

@dataclass
class NodeTag:
    CLASS_ID: int = 0x0F05  # canonical concept `osm_element_tag`
    node: Optional[int] = None

@dataclass
class Note:
    CLASS_ID: int = 0x0F08  # canonical concept `osm_note`
    author: Optional[int] = None
    comments: List[int] = field(default_factory=list)
    all_comments: List[int] = field(default_factory=list)
    subscriptions: List[int] = field(default_factory=list)
    subscribers: List[int] = field(default_factory=list)

@dataclass
class NoteComment:
    note: Optional[int] = None
    author: Optional[int] = None

@dataclass
class NoteSubscription:
    user: Optional[int] = None
    note: Optional[int] = None

@dataclass
class Oauth2Application:
    owner: Optional[int] = None

@dataclass
class OldNode:
    CLASS_ID: int = 0x0F01  # canonical concept `osm_node`
    changeset: Optional[int] = None
    redaction: Optional[int] = None
    current_node: Optional[int] = None
    old_tags: List[int] = field(default_factory=list)

@dataclass
class OldNodeTag:
    CLASS_ID: int = 0x0F05  # canonical concept `osm_element_tag`
    old_node: Optional[int] = None

@dataclass
class OldRelation:
    CLASS_ID: int = 0x0F03  # canonical concept `osm_relation`
    changeset: Optional[int] = None
    redaction: Optional[int] = None
    current_relation: Optional[int] = None
    old_members: List[int] = field(default_factory=list)
    old_tags: List[int] = field(default_factory=list)

@dataclass
class OldRelationMember:
    CLASS_ID: int = 0x0F06  # canonical concept `osm_relation_member`
    old_relation: Optional[int] = None
    member: Optional[int] = None

@dataclass
class OldRelationTag:
    CLASS_ID: int = 0x0F05  # canonical concept `osm_element_tag`
    old_relation: Optional[int] = None

@dataclass
class OldWay:
    CLASS_ID: int = 0x0F02  # canonical concept `osm_way`
    changeset: Optional[int] = None
    redaction: Optional[int] = None
    current_way: Optional[int] = None
    old_nodes: List[int] = field(default_factory=list)
    old_tags: List[int] = field(default_factory=list)

@dataclass
class OldWayNode:
    CLASS_ID: int = 0x0F07  # canonical concept `osm_way_node`
    old_way: Optional[int] = None
    node: Optional[int] = None
    way: Optional[int] = None

@dataclass
class OldWayTag:
    CLASS_ID: int = 0x0F05  # canonical concept `osm_element_tag`
    old_way: Optional[int] = None

@dataclass
class Redaction:
    user: Optional[int] = None
    old_nodes: List[int] = field(default_factory=list)
    old_ways: List[int] = field(default_factory=list)
    old_relations: List[int] = field(default_factory=list)

@dataclass
class Relation:
    CLASS_ID: int = 0x0F03  # canonical concept `osm_relation`
    changeset: Optional[int] = None
    old_relations: List[int] = field(default_factory=list)
    relation_members: List[int] = field(default_factory=list)
    element_tags: List[int] = field(default_factory=list)
    containing_relation_members: List[int] = field(default_factory=list)
    containing_relations: List[int] = field(default_factory=list)

@dataclass
class RelationMember:
    CLASS_ID: int = 0x0F06  # canonical concept `osm_relation_member`
    relation: Optional[int] = None
    member: Optional[int] = None

@dataclass
class RelationTag:
    CLASS_ID: int = 0x0F05  # canonical concept `osm_element_tag`
    relation: Optional[int] = None

@dataclass
class Report:
    issue: Optional[int] = None
    user: Optional[int] = None

@dataclass
class SocialLink:
    user: Optional[int] = None

@dataclass
class SpammyPhrase:
    pass

@dataclass
class Trace:
    CLASS_ID: int = 0x0F09  # canonical concept `osm_gpx_trace`
    user: Optional[int] = None
    tags: List[int] = field(default_factory=list)
    points: List[int] = field(default_factory=list)

@dataclass
class Tracepoint:
    trace: Optional[int] = None

@dataclass
class Tracetag:
    trace: Optional[int] = None

@dataclass
class User:
    CLASS_ID: int = 0x0F0A  # canonical concept `osm_user`
    traces: List[int] = field(default_factory=list)
    diary_entries: List[int] = field(default_factory=list)
    diary_comments: List[int] = field(default_factory=list)
    diary_entry_subscriptions: List[int] = field(default_factory=list)
    diary_subscriptions: List[int] = field(default_factory=list)
    messages: List[int] = field(default_factory=list)
    new_messages: List[int] = field(default_factory=list)
    sent_messages: List[int] = field(default_factory=list)
    muted_messages: List[int] = field(default_factory=list)
    follows: List[int] = field(default_factory=list)
    followings: List[int] = field(default_factory=list)
    preferences: List[int] = field(default_factory=list)
    changesets: List[int] = field(default_factory=list)
    changeset_comments: List[int] = field(default_factory=list)
    changeset_subscriptions: List[int] = field(default_factory=list)
    note_comments: List[int] = field(default_factory=list)
    notes: List[int] = field(default_factory=list)
    note_subscriptions: List[int] = field(default_factory=list)
    subscribed_notes: List[int] = field(default_factory=list)
    oauth2_applications: List[int] = field(default_factory=list)
    access_grants: List[int] = field(default_factory=list)
    access_tokens: List[int] = field(default_factory=list)
    blocks: List[int] = field(default_factory=list)
    blocks_created: List[int] = field(default_factory=list)
    blocks_revoked: List[int] = field(default_factory=list)
    mutes: List[int] = field(default_factory=list)
    muted_users: List[int] = field(default_factory=list)
    roles: List[int] = field(default_factory=list)
    issues: List[int] = field(default_factory=list)
    issue_comments: List[int] = field(default_factory=list)
    reports: List[int] = field(default_factory=list)
    social_links: List[int] = field(default_factory=list)

@dataclass
class UserBlock:
    user: Optional[int] = None
    creator: Optional[int] = None
    revoker: Optional[int] = None

@dataclass
class UserMute:
    owner: Optional[int] = None
    subject: Optional[int] = None

@dataclass
class UserNotificationPreferences:
    pass

@dataclass
class UserPreference:
    user: Optional[int] = None

@dataclass
class UserRole:
    user: Optional[int] = None
    granter: Optional[int] = None

@dataclass
class Way:
    CLASS_ID: int = 0x0F02  # canonical concept `osm_way`
    changeset: Optional[int] = None
    old_ways: List[int] = field(default_factory=list)
    way_nodes: List[int] = field(default_factory=list)
    nodes: List[int] = field(default_factory=list)
    element_tags: List[int] = field(default_factory=list)
    containing_relation_members: List[int] = field(default_factory=list)
    containing_relations: List[int] = field(default_factory=list)

@dataclass
class WayNode:
    CLASS_ID: int = 0x0F07  # canonical concept `osm_way_node`
    way: Optional[int] = None
    node: Optional[int] = None

@dataclass
class WayTag:
    CLASS_ID: int = 0x0F05  # canonical concept `osm_element_tag`
    way: Optional[int] = None

